In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset= pd.read_csv("zoo.csv")

In [3]:
df=pd.DataFrame(dataset[['hair','feathers','eggs','milk','airborne','aquatic','predator','toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize','class_type']])
df.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  class_type  
0         1         0     0     4     0         0        1           1  
1         1         0     0     4     1         0        1           1  
2         0         0     1     0     1         0        0           4  
3         1         0     0     4     0         0        1           1  
4         1         0     0     4     1         0        1           1

In [4]:
from sklearn.preprocessing import StandardScaler
x = pd.DataFrame(df.iloc[:, 0:16].values)
y = pd.DataFrame(df.iloc[:, 16:17].values)
x_enc=x
scaler = StandardScaler()
x_std = scaler.fit_transform(x_enc)
y_enc = le.fit_transform(y.values.ravel())
print (x_enc.head())
print (y.head())


   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
1   1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1
2   0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0
3   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
4   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1
   0
0  1
1  1
2  4
3  1
4  1


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_std, y_enc, test_size = 0.25, random_state = 0)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
clf = LogisticRegression()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
metrics.f1_score(y_test, y_pred,average='macro')

0.9238095238095239

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_pred, y_test))

[[10  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  2]]
0.9615384615384616
